packages:
  - "packages/*"
  - "scripts"
  - "packages/playground/fixtures/**"
  - "packages/create-rspack/**"
  - "npm/*"
  - "crates/node_binding"
  - "crates/rspack_fs_node"
  - "examples/**"
  - "!examples/three"
  - "tests/webpack-examples"
  - "tests/webpack-test"
  - "tests/plugin-test"
  - "tests/webpack-cli-test"
  - "tests/diff-test/*"

catalog:
  react: 18.0.0
  react-dom: 18.0.0
  react-refresh: 0.14.0