name: Download Artifact

description: Download file to local or artifact to quickly share files between jobs

inputs:
  type:
    description: "Use github, local or lynx cache"
    required: true
    type: string
    choices:
      - github
      - local
      - lynx
  name:
    description: "Artifact name"
    default: "artifact"
  path:
    description: "Destination path"
    required: true

runs:
  using: composite
  steps:
    - name: Download artifact from github
      uses: actions/download-artifact@v4.1.7
      if: ${{ inputs.type == 'github' }}
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
    - name: Download artifact from local
      if: ${{ inputs.type == 'local' }}
      shell: bash
      run: |
        set -e
        save_dir=$HOME/.cache/runner/${{ github.repository_id }}-${{ github.sha }}-${{ inputs.name }}
        # download file
        ln -sf $save_dir/* ${{ inputs.path }}
        echo "ln -sf $save_dir/* ${{ inputs.path }}"
    - name: Download artifact from lynx
      if: ${{ inputs.type == 'lynx' }}
      uses: lynx-infra/cache/restore@main
      with:
        path: ${{ inputs.path }}
        key: rust-artifact-${{ github.repository_id }}-${{ github.sha }}-${{ inputs.name }}
        restore-keys: |
          rust-artifact-${{ github.repository_id }}-${{ github.sha }}-${{ inputs.name }}
      env:
        ACCESS_KEY: ${{ env.TOS_ACCESS_KEY }}
        SECRET_KEY: ${{ env.TOS_SECRET_KEY }}
        BUCKET_NAME: ${{ env.TOS_BUCKET_NAME }}
        REGION: ${{ env.TOS_REGION }}
