name: Get Runner Labels

on:
  workflow_call:
    inputs:
      force-use-github-runner:
        type: boolean
        description: "Force use github runner"
        required: false
        default: false
    outputs:
      LINUX_RUNNER_LABELS:
        description: "linux runner labels"
        value: ${{ jobs.main.outputs.LINUX_RUNNER_LABELS }}
      MACOS_RUNNER_LABELS:
        description: "macos runner labels"
        value: ${{ jobs.main.outputs.MACOS_RUNNER_LABELS }}
      WINDOWS_RUNNER_LABELS:
        description: "windows runner labels"
        value: ${{ jobs.main.outputs.WINDOWS_RUNNER_LABELS }}

jobs:
  main:
    name: Get Runner Labels
    runs-on: [self-hosted, Linux, ci]
    outputs:
      LINUX_RUNNER_LABELS: ${{ steps.run.outputs.LINUX_RUNNER_LABELS }}
      LINUX_RUNNER_EPHEMERAL: ${{ steps.run.outputs.LINUX_RUNNERX_EPHEMERAL }}

      MACOS_RUNNER_LABELS: ${{ steps.run.outputs.MACOS_RUNNER_LABELS }}
      MACOS_RUNNER_EPHEMERAL: ${{ steps.run.outputs.MACOS_RUNNER_EPHEMERAL }}

      WINDOWS_RUNNER_LABELS: ${{ steps.run.outputs.WINDOWS_RUNNER_LABELS }}
      WINDOWS_RUNNER_EPHEMERAL: ${{ steps.run.outputs.WINDOWS_RUNNER_EPHEMERAL }}
    steps:
      - id: run
        shell: bash
        run: |
          if ${{ !inputs.force-use-github-runner }}; then
            LINUX_RUNNER_LABELS='${{ vars.LINUX_RUNNER_LABELS }}';
            MACOS_RUNNER_LABELS='${{ vars.MACOS_RUNNER_LABELS }}';
            WINDOWS_RUNNER_LABELS='${{ vars.WINDOWS_RUNNER_LABELS }}';
          fi
          # set default value
          if [[ -z "$LINUX_RUNNER_LABELS" ]]; then
            LINUX_RUNNER_LABELS='"ubuntu-latest"';
          fi
          if [[ -z "$MACOS_RUNNER_LABELS" ]]; then
            MACOS_RUNNER_LABELS='"macos-latest"';
          fi
          if [[ -z "$WINDOWS_RUNNER_LABELS" ]]; then
            WINDOWS_RUNNER_LABELS='"windows-latest"';
          fi

          if [[ "$LINUX_RUNNER_LABELS" == rspack-* ]]; then
            LINUX_RUNNER_EPHEMERAL="false"
          else
            LINUX_RUNNER_EPHEMERAL="true"
          fi
          if [[ "$LINUX_RUNNER_LABELS" == rspack-* ]]; then
            MACOS_RUNNER_EPHEMERAL="false"
          else
            MACOS_RUNNER_EPHEMERAL="true"
          fi

          # set output
          echo "LINUX_RUNNER_LABELS=$LINUX_RUNNER_LABELS" >> "$GITHUB_OUTPUT"
          echo "LINUX_RUNNER_EPHEMERAL=$LINUX_RUNNER_EPHEMERAL" >> "$GITHUB_OUTPUT"

          echo "MACOS_RUNNER_LABELS=$MACOS_RUNNER_LABELS" >> "$GITHUB_OUTPUT"
          echo "MACOS_RUNNER_EPHEMERAL=$MACOS_RUNNER_EPHEMERAL" >> "$GITHUB_OUTPUT"

          echo "WINDOWS_RUNNER_LABELS='"volc-windows-2022-medium"'" >> "$GITHUB_OUTPUT"
          echo "WINDOWS_RUNNER_EPHEMERAL='true'" >> "$GITHUB_OUTPUT"
