name: Get Runner Labels

on:
  workflow_call:
    inputs:
      force-use-github-runner:
        type: boolean
        description: "Force use github runner"
        required: false
        default: false
    outputs:
      LINUX_RUNNER_LABELS:
        description: "linux runner labels"
        value: ${{ jobs.main.outputs.LINUX_RUNNER_LABELS }}
      LINUX_RUNNER_TYPE:
        description: "linux runner type"
        value: ${{ jobs.main.outputs.LINUX_RUNNER_TYPE }}
      LINUX_CACHE_TYPE:
        description: "cache type used for linux runner"
        value: ${{ jobs.main.outputs.LINUX_CACHE_TYPE }}
      MACOS_RUNNER_LABELS:
        description: "macos runner labels"
        value: ${{ jobs.main.outputs.MACOS_RUNNER_LABELS }}
      MACOS_RUNNER_TYPE:
        description: "macos runner type"
        value: ${{ jobs.main.outputs.MACOS_RUNNER_TYPE }}
      MACOS_CACHE_TYPE:
        description: "cache type used for macos runner"
        value: ${{ jobs.main.outputs.MACOS_CACHE_TYPE }}
      WINDOWS_RUNNER_LABELS:
        description: "windows runner labels"
        value: ${{ jobs.main.outputs.WINDOWS_RUNNER_LABELS }}
      WINDOWS_RUNNER_TYPE:
        description: "windows runner type"
        value: ${{ jobs.main.outputs.WINDOWS_RUNNER_TYPE }}
      WINDOWS_CACHE_TYPE:
        description: "cache type used for windows runner"
        value: ${{ jobs.main.outputs.WINDOWS_CACHE_TYPE }}

jobs:
  main:
    name: Get Runner Labels
    runs-on: [self-hosted, Linux, ci]
    outputs:
      LINUX_RUNNER_LABELS: ${{ steps.run.outputs.LINUX_RUNNER_LABELS }}
      LINUX_RUNNER_TYPE: ${{ steps.run.outputs.LINUX_RUNNER_TYPE }}
      LINUX_CACHE_TYPE: ${{ steps.run.outputs.LINUX_CACHE_TYPE }}

      MACOS_RUNNER_LABELS: ${{ steps.run.outputs.MACOS_RUNNER_LABELS }}
      MACOS_RUNNER_TYPE: ${{ steps.run.outputs.MACOS_RUNNER_TYPE }}
      MACOS_CACHE_TYPE: ${{ steps.run.outputs.MACOS_CACHE_TYPE }}

      WINDOWS_RUNNER_LABELS: ${{ steps.run.outputs.WINDOWS_RUNNER_LABELS }}
      WINDOWS_RUNNER_TYPE: ${{ steps.run.outputs.WINDOWS_RUNNER_TYPE }}
      WINDOWS_CACHE_TYPE: ${{ steps.run.outputs.WINDOWS_CACHE_TYPE }}
    steps:
      - id: run
        shell: bash
        run: |
          if ${{ !inputs.force-use-github-runner }}; then
            LINUX_RUNNER_LABELS='${{ vars.LINUX_RUNNER_LABELS }}';
            MACOS_RUNNER_LABELS='${{ vars.MACOS_RUNNER_LABELS }}';
            WINDOWS_RUNNER_LABELS='${{ vars.WINDOWS_RUNNER_LABELS }}';
          fi

          # set default value
          if [[ -z "$LINUX_RUNNER_LABELS" ]]; then
            LINUX_RUNNER_LABELS='"ubuntu-latest"';
          fi
          if [[ -z "$MACOS_RUNNER_LABELS" ]]; then
            MACOS_RUNNER_LABELS='"macos-latest"';
          fi
          if [[ -z "$WINDOWS_RUNNER_LABELS" ]]; then
            WINDOWS_RUNNER_LABELS='"windows-latest"';
          fi

          if [[ "$LINUX_RUNNER_LABELS" == rspack-* ]]; then
            LINUX_RUNNER_TYPE="hosted"
            LINUX_CACHE_TYPE="hosted"
          else
            LINUX_RUNNER_TYPE="github"
            LINUX_CACHE_TYPE="github"
          fi

          if [[ "$MACOS_RUNNER_LABELS" == rspack-* ]]; then
            MACOS_RUNNER_EPHEMERAL="hosted"
            MACOS_CACHE_TYPE="hosted"
          else
            MACOS_RUNNER_EPHEMERAL="github"
            MACOS_CACHE_TYPE="github"
          fi

          # set output
          echo "LINUX_RUNNER_LABELS=$LINUX_RUNNER_LABELS" >> "$GITHUB_OUTPUT"
          echo "LINUX_RUNNER_TYPE=$LINUX_RUNNER_TYPE" >> "$GITHUB_OUTPUT"
          echo "LINUX_CACHE_TYPE=$LINUX_CACHE_TYPE" >> "$GITHUB_OUTPUT"

          echo "MACOS_RUNNER_LABELS=$MACOS_RUNNER_LABELS" >> "$GITHUB_OUTPUT"
          echo "MACOS_RUNNER_EPHEMERAL=$MACOS_RUNNER_EPHEMERAL" >> "$GITHUB_OUTPUT"
          echo "MACOS_CACHE_TYPE=$MACOS_CACHE_TYPE" >> "$GITHUB_OUTPUT"

          # TODO: test
          echo "WINDOWS_RUNNER_LABELS='"volc-windows-2022-medium"'" >> "$GITHUB_OUTPUT"
          echo "WINDOWS_RUNNER_TYPE=k8s" >> "$GITHUB_OUTPUT"
          echo "WINDOWS_CACHE_TYPE=lynx" >> "$GITHUB_OUTPUT"
